# Northplane build (SPEC §7.1: one static binary including the UI)
VERSION ?= 1.0.0-dev
LDFLAGS  = -ldflags "-X main.version=$(VERSION)"

.PHONY: all web docs docs-dev build test race fmt docker clean dev dev-reset types types-check e2e

all: web docs build

# Typed codegen (ADR-10): the Go API is the single source of truth for the
# wire shapes. `make types` dumps the OpenAPI 3.1 spec straight from the route
# registry (no running server — see `northplaned openapi`) and runs it through
# openapi-typescript into web/src/types.gen.ts. The frontend's curated
# types.ts then conforms to that generated file at compile time
# (web/src/types.gen.conformance.ts), so a backend change that the frontend
# hasn't caught up to becomes a TypeScript build error rather than a silent
# runtime bug. Deterministic: spec schemas/routes are sorted in Go and
# openapi-typescript emits keys sorted, so re-running produces no diff.
types:
	go run ./cmd/northplaned openapi > /tmp/np-openapi.json
	cp /tmp/np-openapi.json docs/src/assets/openapi.json
	cd web && npx --no-install openapi-typescript /tmp/np-openapi.json -o src/types.gen.ts
	printf '%s\n' \
	  '// Code generated by `make types` from the Northplane OpenAPI 3.1 spec.' \
	  '// DO NOT EDIT. Source of truth: the Go API (internal/api). Regenerate' \
	  '// with `make types`; CI fails (`make types-check`) if this drifts.' \
	  | cat - web/src/types.gen.ts > web/src/types.gen.ts.tmp \
	  && mv web/src/types.gen.ts.tmp web/src/types.gen.ts

# CI drift gate: regenerate the types and fail if the committed files changed.
# A red diff here means the Go API moved but web/src/types.gen.ts (and the
# docs' copy of the spec, which the API reference is rendered from) wasn't
# regenerated/committed — the exact drift this pipeline exists to catch.
types-check: types
	git diff --exit-code -- web/src/types.gen.ts docs/src/assets/openapi.json

# Dev pipeline (hot reload): Vite HMR on :5173 + Go auto-rebuild/restart
# on :8443. State in .dev/ (git-ignored); demo data seeded on first run
# (NP_DEV_DEMO=0 to skip). Ctrl-C stops both processes.
dev:
	./scripts/dev.sh

# Wipe the dev state (SQLite, config, key) for a fresh start.
dev-reset:
	/bin/rm -rf .dev

web:
	cd web && npm ci --silent && npm run build
	/bin/rm -rf internal/web/dist
	cp -r web/dist internal/web/dist

# Product documentation (Astro Starlight, docs/): build the static site and
# stage it for go:embed in internal/docs/dist, which is git-ignored apart from
# its .gitkeep — a plain `go build` still compiles (and answers /docs/ with a
# "run make docs" 501) while the Docker image and release binaries carry the
# full manual. The build fails on broken internal links (starlight-links-validator).
docs:
	cd docs && npm ci --silent && npm run build:embed
	/bin/rm -rf internal/docs/dist
	mkdir -p internal/docs/dist
	cp -r docs/dist/. internal/docs/dist/
	touch internal/docs/dist/.gitkeep

# Live-reloading docs authoring server (http://localhost:4321/docs/).
docs-dev:
	cd docs && npm run dev

build:
	go build $(LDFLAGS) -o bin/northplaned ./cmd/northplaned
	go build $(LDFLAGS) -o bin/np ./cmd/np
	go build $(LDFLAGS) -o bin/np-agent ./cmd/np-agent
	go build $(LDFLAGS) -o bin/np-gen ./cmd/np-gen

test:
	go vet ./...
	go test ./...

# Race-enabled run of the whole suite (what CI runs).
race:
	go test -race ./...

# End-to-end browser tests: rebuild the embedded UI + binary, then drive the
# real --demo server through Chromium (Playwright). global-setup boots/teardowns
# an isolated demo server, so this is the one command that proves the whole
# product works end to end. First run installs the Chromium binary.
e2e: web
	go build $(LDFLAGS) -o bin/northplaned ./cmd/northplaned
	cd web && npx playwright install chromium && npm run test:e2e

fmt:
	gofmt -w cmd internal

docker:
	docker build --build-arg VERSION=$(VERSION) -t northplane:$(VERSION) .

clean:
	/bin/rm -rf bin web/dist internal/web/dist docs/dist internal/docs/dist
	mkdir -p internal/web/dist && echo '<!doctype html><title>Northplane</title>' > internal/web/dist/index.html
	mkdir -p internal/docs/dist && touch internal/docs/dist/.gitkeep
