#!/usr/bin/env bash
# Northplane dev pipeline (`make dev`):
#
#   Vite dev server (HMR)  →  http://localhost:5173   (edit web/src → instant hot reload)
#   northplaned (Go)       →  http://127.0.0.1:8443   (edit cmd/ or internal/ → auto rebuild+restart)
#
# The Vite server proxies every backend route (/api, /login, /auth, /status,
# /setup, /mcp, health) to the Go process, so the SPA at :5173 talks to a
# fully live backend — cookies stay same-origin, SSE streams through.
#
# State lives in .dev/ (config, secret key, SQLite, logs, built binary) and
# is git-ignored. First start seeds the idempotent demo environment
# (NP_DEV_DEMO=0 to skip). No external watcher tools needed: the Go watcher
# is a portable poll over the source tree (find + shasum).
#
# Implementation notes (deliberately macOS-bash-3.2-safe):
# - Servers append to .dev/*.log via plain redirects so $! is the real
#   server pid (process substitution gives a wrong $! on bash 3.2).
# - stop_backend() kills by LISTENING PORT, not just by pid, and blocks
#   until the port is actually free — otherwise the next bind races a
#   lingering listener ("address already in use").
set -euo pipefail
cd "$(dirname "$0")/.."

DEV_DIR=${NP_DEV_DIR:-.dev}
LISTEN=${NP_DEV_LISTEN:-127.0.0.1:8443}
WEB_PORT=${NP_DEV_WEB_PORT:-5173}
DEMO=${NP_DEV_DEMO:-1}
PORT=${LISTEN##*:}
mkdir -p "$DEV_DIR"

# ── single instance ────────────────────────────────────────────────────
# A second `make dev` must not run concurrently: two watcher loops both
# kill "whatever listens" on the API port and start their own, so the
# backend flaps and every request hangs/ECONNREFUSEs. Take over from a
# previous run by killing its process (its EXIT trap tears down its vite +
# backend), then claim the lock.
LOCK="$DEV_DIR/dev.pid"
if [ -f "$LOCK" ]; then
  OLD=$(cat "$LOCK" 2>/dev/null || true)
  if [ -n "${OLD:-}" ] && [ "$OLD" != "$$" ] && kill -0 "$OLD" 2>/dev/null; then
    echo "[dev] another dev session (pid $OLD) is running — taking over…"
    kill "$OLD" 2>/dev/null || true
    for _ in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
      kill -0 "$OLD" 2>/dev/null || break
      sleep 0.2
    done
  fi
fi
echo $$ > "$LOCK"

# ── one-time bootstrap: secret key + config ────────────────────────────
if [ ! -f "$DEV_DIR/secret.key" ]; then
  head -c 32 /dev/urandom | xxd -p -c 64 > "$DEV_DIR/secret.key"
  chmod 600 "$DEV_DIR/secret.key"
fi
if [ ! -f "$DEV_DIR/config.yaml" ]; then
  cat > "$DEV_DIR/config.yaml" <<EOF
# Northplane DEV config (generated by scripts/dev.sh — safe to edit)
listen: "$LISTEN"
baseUrl: "http://localhost:$WEB_PORT"
dataDir: $DEV_DIR/data
logLevel: info
logFormat: text
secretKeyFile: $DEV_DIR/secret.key
EOF
  echo "[dev] wrote $DEV_DIR/config.yaml"
fi

# go:embed needs *some* dist; the stub is enough — the real UI comes from Vite.
if [ ! -f internal/web/dist/index.html ]; then
  mkdir -p internal/web/dist
  echo '<!doctype html><title>Northplane</title>' > internal/web/dist/index.html
fi

# frontend deps — (re)install when node_modules is missing OR the lockfile
# changed (e.g. after a git pull that added a dependency), so a stale tree
# doesn't fail Vite with "module not found".
if [ ! -d web/node_modules ] || [ web/package-lock.json -nt web/node_modules/.package-lock.json ]; then
  echo "[dev] installing frontend dependencies (npm ci)…"
  (cd web && npm ci --silent)
fi

# ── process management ─────────────────────────────────────────────────
# kill_tree: npm/vite fork children; killing only $! would orphan them.
kill_tree() {
  local pid=$1 kid
  for kid in $(pgrep -P "$pid" 2>/dev/null); do kill_tree "$kid"; done
  kill "$pid" 2>/dev/null || true
}

BACKEND_PID=""
VITE_PID=""

# stop_backend kills whatever LISTENS on the API port (covers stale
# servers from crashed runs too) and blocks until the port is free;
# escalates to SIGKILL after ~5 s.
stop_backend() {
  local pids p n=0
  pids=$(lsof -ti tcp:"$PORT" -sTCP:LISTEN 2>/dev/null || true)
  for p in $pids $BACKEND_PID; do kill "$p" 2>/dev/null || true; done
  while lsof -ti tcp:"$PORT" -sTCP:LISTEN >/dev/null 2>&1; do
    n=$((n + 1))
    if [ "$n" -ge 50 ]; then
      lsof -ti tcp:"$PORT" -sTCP:LISTEN | xargs kill -9 2>/dev/null || true
      n=0
    fi
    sleep 0.1
  done
  if [ -n "$BACKEND_PID" ]; then
    wait "$BACKEND_PID" 2>/dev/null || true
    BACKEND_PID=""
  fi
}

cleanup() {
  trap - EXIT INT TERM
  stop_backend
  [ -n "$VITE_PID" ] && kill_tree "$VITE_PID"
  pkill -f "tail -n +1 -f $DEV_DIR/" 2>/dev/null || true
  rm -f "$LOCK"
  wait 2>/dev/null || true
  echo "[dev] stopped."
}
trap cleanup EXIT INT TERM

# prefix is a line-buffered tagger (sed/awk buffer when piped).
prefix() { while IFS= read -r line; do printf '%s %s\n' "$1" "$line"; done; }

# Servers append to log files; persistent tails tag the streams.
: > "$DEV_DIR/api.log"
: > "$DEV_DIR/web.log"
tail -n +1 -f "$DEV_DIR/api.log" | prefix '[api]' &
tail -n +1 -f "$DEV_DIR/web.log" | prefix '[web]' &

# clear any stale dev server from a crashed previous run
stop_backend

# ── Vite (frontend HMR) ────────────────────────────────────────────────
(cd web && exec env NP_API="http://$LISTEN" \
  npm run dev -- --port "$WEB_PORT" --strictPort) >> "$DEV_DIR/web.log" 2>&1 &
VITE_PID=$!

# ── Go backend: rebuild + restart on source change ─────────────────────
src_hash() {
  { find cmd internal -name '*.go' -not -name '*_test.go' -print0 2>/dev/null \
      | xargs -0 shasum 2>/dev/null; shasum go.mod go.sum 2>/dev/null; } | shasum | cut -d' ' -f1
}

DEMO_FLAG=""
[ "$DEMO" = "1" ] && DEMO_FLAG="-demo"

start_backend() {
  "$DEV_DIR/northplaned" serve -config "$DEV_DIR/config.yaml" $DEMO_FLAG \
    >> "$DEV_DIR/api.log" 2>&1 &
  BACKEND_PID=$!
}

# wait_healthy polls /readyz (storage + eventbus ready), not /healthz
# (which goes green the instant the listener binds, before the DB can
# serve) so the first proxied request after a restart doesn't race
# warm-up. Fails fast if the process died (bad config, port conflict) so
# a broken start is loud, not silent.
wait_healthy() {
  local n=0
  while [ "$n" -lt 100 ]; do
    curl -sf -o /dev/null "http://$LISTEN/readyz" 2>/dev/null && return 0
    kill -0 "$BACKEND_PID" 2>/dev/null || return 1
    n=$((n + 1))
    sleep 0.1
  done
  return 1
}

LAST=""
echo "[dev] UI  → http://localhost:$WEB_PORT  (hot reload)"
echo "[dev] API → http://$LISTEN  (auto rebuild+restart)"
[ "$DEMO" = "1" ] && echo "[dev] demo users: demo-operator / operator-demo-2026!  ·  demo-viewer / viewer-demo-2026!"
while :; do
  CUR=$(src_hash)
  if [ "$CUR" != "$LAST" ]; then
    LAST="$CUR"
    echo "[dev] building backend…"
    if go build -o "$DEV_DIR/northplaned.new" ./cmd/northplaned; then
      mv "$DEV_DIR/northplaned.new" "$DEV_DIR/northplaned"
      stop_backend
      start_backend
      if wait_healthy; then
        echo "[dev] ✓ backend up (pid $BACKEND_PID)"
      else
        echo "[dev] ✗ backend failed to start — see [api] output above"
      fi
    else
      echo "[dev] ✗ build failed — previous server keeps running"
    fi
  fi
  sleep "${NP_DEV_POLL:-1}"
done
