// Package config loads the deliberately minimal bootstrap configuration
// (SPEC §15.2): only what must exist before the API is reachable lives
// in config.yaml; everything else is API/bundle-managed. NORTHPLANE_*
// environment variables override file values for container use.
package config

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Config is the bootstrap configuration.
type Config struct {
	Listen  string `yaml:"listen"`  // ":8443"
	BaseURL string `yaml:"baseUrl"` // external URL for links/ack/OIDC redirect

	DataDir string `yaml:"dataDir"` // /var/lib/northplane

	// TrustProxy: when true, honour X-Forwarded-Proto/-For from a TLS-
	// terminating reverse proxy (sets Secure cookies + HSTS + correct
	// client IP even though the local listener is plaintext). Only enable
	// when the proxy is trusted and strips inbound forwarded headers.
	TrustProxy bool `yaml:"trustProxy"`

	Storage StorageConfig `yaml:"storage"`
	TLS     TLSConfig     `yaml:"tls"`
	OIDC    OIDCConfig    `yaml:"oidc"`
	AI      AIConfig      `yaml:"ai"`
	Backup  BackupConfig  `yaml:"backup"`

	// DeadManURL: outgoing heartbeat ping (healthchecks.io-compatible,
	// SPEC §14.2 / P7). Empty = disabled.
	DeadManURL      string        `yaml:"deadManUrl"`
	DeadManInterval time.Duration `yaml:"deadManInterval"`

	PluginsDir   string `yaml:"pluginsDir"`   // Nagios plugins root
	PluginsAllow []string `yaml:"pluginsAllow"` // optional allowlist (basenames)

	ExecPoolSize int `yaml:"execPoolSize"` // 0 = min(256, 32×vCPU) (SPEC §7.4)

	LogLevel  string `yaml:"logLevel"`  // debug|info|warn|error
	LogFormat string `yaml:"logFormat"` // json|text

	// SecretKeyFile holds the 32-byte master key (hex) for AES-256-GCM
	// secrets-at-rest (SPEC §13.2). Generated by `northplaned init`.
	SecretKeyFile string `yaml:"secretKeyFile"`
}

// StorageConfig selects the relational backend (SPEC §7.3): empty DSN ⇒
// embedded SQLite under DataDir; "postgres://…" ⇒ PostgreSQL.
type StorageConfig struct {
	DSN string `yaml:"dsn"`
	// EventRetention: months of event segments/partitions to keep.
	EventRetentionMonths int `yaml:"eventRetentionMonths"`
}

// TLSConfig: certificate pair or autocert; plain HTTP only for
// localhost/dev (A-15.10: no plaintext fallback in production).
type TLSConfig struct {
	CertFile string `yaml:"certFile"`
	KeyFile  string `yaml:"keyFile"`
	// Insecure allows ListenAndServe without TLS — refused unless the
	// listener is loopback or explicitly forced (dev mode).
	Insecure bool `yaml:"insecure"`
}

// OIDCConfig for human SSO (SPEC §11.2).
type OIDCConfig struct {
	Issuer       string   `yaml:"issuer"`
	ClientID     string   `yaml:"clientId"`
	ClientSecret string   `yaml:"clientSecret"`
	Scopes       []string `yaml:"scopes"`       // default: openid profile email groups
	GroupsClaim  string   `yaml:"groupsClaim"`  // default "groups"
	AdminGroup   string   `yaml:"adminGroup"`   // bootstrap mapping
}

// AIConfig per SPEC §10.2.
type AIConfig struct {
	Provider  string `yaml:"provider"` // anthropic | azure-openai | openai-compat | none
	Endpoint  string `yaml:"endpoint"`
	APIKeyEnv string `yaml:"apiKeyEnv"` // env var holding the key (never the key itself)
	APIKey    string `yaml:"apiKey"`    // discouraged; for gateways with static keys
	Model     string `yaml:"model"`
	ModelDeep string `yaml:"modelDeep"`
	MaxMonthlyTokens int64 `yaml:"maxMonthlyTokens"`
	Redaction RedactionConfig `yaml:"redaction"`
}

// RedactionConfig drives the PII pipeline before any LLM call (§10.1/§13.6).
type RedactionConfig struct {
	Hostnames      string   `yaml:"hostnames"` // "" | "pseudonymize"
	CustomPatterns []string `yaml:"customPatterns"`
}

// BackupConfig for continuous backup (SPEC §14.2).
type BackupConfig struct {
	Target   string        `yaml:"target"` // directory or s3://… (dir in v1)
	Interval time.Duration `yaml:"interval"`
}

// DefaultDataDir returns the platform default data directory:
// /var/lib/northplane when running as root (the systemd/production
// case), otherwise a per-user directory so `northplaned` runs without
// privileges (macOS: ~/Library/Application Support/northplane, Linux:
// $XDG_DATA_HOME/northplane or ~/.local/share/northplane).
func DefaultDataDir() string {
	if os.Geteuid() == 0 {
		return "/var/lib/northplane"
	}
	if runtime.GOOS != "darwin" {
		if xdg := os.Getenv("XDG_DATA_HOME"); xdg != "" {
			return filepath.Join(xdg, "northplane")
		}
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".local", "share", "northplane")
		}
	}
	if dir, err := os.UserConfigDir(); err == nil {
		return filepath.Join(dir, "northplane")
	}
	return "/var/lib/northplane"
}

// DefaultConfigDir is where `northplaned init` writes config.yaml and
// secret.key: /etc/northplane as root, the per-user config directory
// otherwise (macOS: ~/Library/Application Support/northplane, Linux:
// ~/.config/northplane).
func DefaultConfigDir() string {
	if os.Geteuid() == 0 {
		return "/etc/northplane"
	}
	if dir, err := os.UserConfigDir(); err == nil {
		return filepath.Join(dir, "northplane")
	}
	return "/etc/northplane"
}

// DefaultConfigPath resolves the bootstrap config file: the system path
// when running as root or when it exists, the per-user path otherwise.
func DefaultConfigPath() string { return defaultPath("config.yaml") }

// DefaultAgentConfigPath is the np-agent equivalent of DefaultConfigPath.
func DefaultAgentConfigPath() string { return defaultPath("agent.yaml") }

func defaultPath(file string) string {
	system := filepath.Join("/etc/northplane", file)
	if os.Geteuid() == 0 {
		return system
	}
	if _, err := os.Stat(system); err == nil {
		return system
	}
	return filepath.Join(DefaultConfigDir(), file)
}

// Defaults returns the development-friendly default configuration.
// Listen binds loopback only: plaintext HTTP is acceptable there, and
// exposing the server requires an explicit listen + TLS decision
// (A-15.10: no accidental plaintext in production).
func Defaults() Config {
	return Config{
		Listen:          "127.0.0.1:8443",
		DataDir:         DefaultDataDir(),
		LogLevel:        "info",
		LogFormat:       "json",
		DeadManInterval: time.Minute,
		Storage:         StorageConfig{EventRetentionMonths: 12},
		OIDC:            OIDCConfig{Scopes: []string{"openid", "profile", "email", "groups"}, GroupsClaim: "groups"},
		AI:              AIConfig{Provider: "none", Model: "claude-sonnet-4-6"},
		Backup:          BackupConfig{Interval: 5 * time.Minute},
	}
}

// Load reads path (if it exists), then applies NORTHPLANE_* overrides.
func Load(path string) (Config, error) {
	cfg := Defaults()
	if path != "" {
		b, err := os.ReadFile(path)
		switch {
		case err == nil:
			dec := yaml.NewDecoder(strings.NewReader(string(b)))
			dec.KnownFields(true)
			if err := dec.Decode(&cfg); err != nil && !errors.Is(err, io.EOF) {
				// io.EOF = empty/comment-only file: keep defaults rather
				// than refusing to start.
				return cfg, fmt.Errorf("config %s: %w", path, err)
			}
		case os.IsNotExist(err):
			// fine: env/defaults only
		default:
			return cfg, err
		}
	}
	applyEnv(&cfg)
	if cfg.PluginsDir == "" {
		cfg.PluginsDir = firstExisting(
			"/usr/lib/nagios/plugins", "/usr/lib64/nagios/plugins",
			"/usr/local/libexec/nagios", "/opt/homebrew/libexec",
			filepath.Join(cfg.DataDir, "plugins"),
		)
	}
	return cfg, nil
}

func firstExisting(paths ...string) string {
	for _, p := range paths {
		if st, err := os.Stat(p); err == nil && st.IsDir() {
			return p
		}
	}
	return paths[len(paths)-1]
}

// applyEnv maps NORTHPLANE_SECTION_FIELD → fields (SPEC §15.2).
func applyEnv(c *Config) {
	str := func(key string, dst *string) {
		if v, ok := os.LookupEnv(key); ok {
			*dst = v
		}
	}
	str("NORTHPLANE_LISTEN", &c.Listen)
	str("NORTHPLANE_BASE_URL", &c.BaseURL)
	str("NORTHPLANE_DATA_DIR", &c.DataDir)
	str("NORTHPLANE_STORAGE_DSN", &c.Storage.DSN)
	str("NORTHPLANE_TLS_CERT_FILE", &c.TLS.CertFile)
	str("NORTHPLANE_TLS_KEY_FILE", &c.TLS.KeyFile)
	if v, ok := os.LookupEnv("NORTHPLANE_TLS_INSECURE"); ok {
		c.TLS.Insecure, _ = strconv.ParseBool(v)
	}
	if v, ok := os.LookupEnv("NORTHPLANE_TRUST_PROXY"); ok {
		c.TrustProxy, _ = strconv.ParseBool(v)
	}
	str("NORTHPLANE_OIDC_ISSUER", &c.OIDC.Issuer)
	str("NORTHPLANE_OIDC_CLIENT_ID", &c.OIDC.ClientID)
	str("NORTHPLANE_OIDC_CLIENT_SECRET", &c.OIDC.ClientSecret)
	str("NORTHPLANE_AI_PROVIDER", &c.AI.Provider)
	str("NORTHPLANE_AI_ENDPOINT", &c.AI.Endpoint)
	str("NORTHPLANE_AI_MODEL", &c.AI.Model)
	str("NORTHPLANE_AI_API_KEY_ENV", &c.AI.APIKeyEnv)
	str("NORTHPLANE_PLUGINS_DIR", &c.PluginsDir)
	str("NORTHPLANE_LOG_LEVEL", &c.LogLevel)
	str("NORTHPLANE_LOG_FORMAT", &c.LogFormat)
	str("NORTHPLANE_SECRET_KEY_FILE", &c.SecretKeyFile)
	str("NORTHPLANE_BACKUP_TARGET", &c.Backup.Target)
	str("NORTHPLANE_DEADMAN_URL", &c.DeadManURL)
	if v, ok := os.LookupEnv("NORTHPLANE_EXEC_POOL_SIZE"); ok {
		if n, err := strconv.Atoi(v); err == nil {
			c.ExecPoolSize = n
		}
	}
}

// SQLitePath returns the core database path for embedded mode.
func (c Config) SQLitePath() string { return filepath.Join(c.DataDir, "core.db") }

// TSDBDir returns the metrics engine directory.
func (c Config) TSDBDir() string { return filepath.Join(c.DataDir, "tsdb") }

// ArtifactsDir stores E2E check artifacts (SPEC §8.6).
func (c Config) ArtifactsDir() string { return filepath.Join(c.DataDir, "artifacts") }

// UsePostgres reports whether the DSN selects the PostgreSQL backend.
func (c Config) UsePostgres() bool {
	return strings.HasPrefix(c.Storage.DSN, "postgres://") ||
		strings.HasPrefix(c.Storage.DSN, "postgresql://")
}

// Example renders the commented config file written by `northplaned
// init`. dataDir and secretKeyFile are interpolated directly (no
// post-hoc string replacement) so the generated file is always valid.
func Example(dataDir, secretKeyFile string) string {
	if dataDir == "" {
		dataDir = DefaultDataDir()
	}
	keyLine := ""
	if secretKeyFile != "" {
		keyLine = fmt.Sprintf("secretKeyFile: %q\n", secretKeyFile)
	}
	return `# Northplane bootstrap configuration (SPEC §15.2).
# Only pre-API settings live here — everything else is managed via API,
# UI or config bundles. Environment overrides: NORTHPLANE_*.

# Loopback default. To serve the network, set listen: ":8443" AND
# configure TLS below (plaintext on non-loopback refuses to start).
listen: "127.0.0.1:8443"
#baseUrl: "https://monitoring.example.net"
dataDir: ` + fmt.Sprintf("%q", dataDir) + `
` + keyLine + `
storage:
  # Empty dsn = embedded SQLite under dataDir (default).
  # PostgreSQL server mode: "postgres://np:secret@db:5432/northplane"
  dsn: ""
  eventRetentionMonths: 12

tls:
  certFile: ""
  keyFile: ""
  # insecure: true   # dev only; refused on non-loopback listeners

#oidc:
#  issuer: "https://login.microsoftonline.com/<tenant>/v2.0"
#  clientId: "…"
#  clientSecret: "…"
#  adminGroup: "<entra-group-object-id>"

ai:
  provider: none     # anthropic | azure-openai | openai-compat | none
  #endpoint: "https://api.anthropic.com"
  #apiKeyEnv: ANTHROPIC_API_KEY
  #model: claude-sonnet-4-6
  #modelDeep: claude-opus-4-8
  #maxMonthlyTokens: 50000000

backup:
  target: ""          # directory for continuous backup; empty = disabled
  interval: 5m

#deadManUrl: "https://hc-ping.com/<uuid>"   # SPEC §14.2 dead-man switch
`
}
