// Package config loads the deliberately minimal bootstrap configuration
// (SPEC §15.2): only what must exist before the API is reachable lives
// in config.yaml; everything else is API/bundle-managed. NORTHPLANE_*
// environment variables override file values for container use.
package config

import (
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Config is the bootstrap configuration.
type Config struct {
	Listen  string `yaml:"listen"`  // ":8443"
	BaseURL string `yaml:"baseUrl"` // external URL for links/ack/OIDC redirect

	DataDir string `yaml:"dataDir"` // /var/lib/northplane

	// TrustProxy: when true, honour X-Forwarded-Proto/-For from a TLS-
	// terminating reverse proxy (sets Secure cookies + HSTS + correct
	// client IP even though the local listener is plaintext). Only enable
	// when the proxy is trusted and strips inbound forwarded headers.
	TrustProxy bool `yaml:"trustProxy"`

	Storage    StorageConfig    `yaml:"storage"`
	TLS        TLSConfig        `yaml:"tls"`
	OIDC       OIDCConfig       `yaml:"oidc"`
	LDAP       LDAPConfig       `yaml:"ldap"`
	AI         AIConfig         `yaml:"ai"`
	Backup     BackupConfig     `yaml:"backup"`
	Federation FederationConfig `yaml:"federation"`
	TTS        TTSConfig        `yaml:"tts"`

	// DeadManURL: outgoing heartbeat ping (healthchecks.io-compatible,
	// SPEC §14.2 / P7). Empty = disabled.
	DeadManURL      string        `yaml:"deadManUrl"`
	DeadManInterval time.Duration `yaml:"deadManInterval"`

	PluginsDir   string   `yaml:"pluginsDir"`   // Nagios plugins root
	PluginsAllow []string `yaml:"pluginsAllow"` // optional allowlist (basenames)

	ExecPoolSize int `yaml:"execPoolSize"` // 0 = min(256, 32×vCPU) (SPEC §7.4)

	LogLevel  string `yaml:"logLevel"`  // debug|info|warn|error
	LogFormat string `yaml:"logFormat"` // json|text

	// SecretKeyFile holds the 32-byte master key (hex) for AES-256-GCM
	// secrets-at-rest (SPEC §13.2). Generated by `northplaned init`.
	SecretKeyFile string `yaml:"secretKeyFile"`

	// Demo, when true (env NORTHPLANE_DEMO=true / `demo: true`), seeds the
	// idempotent showcase environment at startup — the same data as
	// `serve --demo`, but driven by config so a container deployment can
	// flip between a demo instance and a real one without changing the
	// command. The env path is guarded (cmd/northplaned): it never seeds on
	// top of a database that already holds real, non-demo hosts.
	Demo bool `yaml:"demo"`

	// AllowSignup, when true (env NORTHPLANE_ALLOW_SIGNUP=true /
	// `allowSignup: true`), exposes a public /register page for
	// self-service account creation. Self-registered accounts always get
	// the viewer role only — an admin promotes them afterwards. Off by
	// default: most installs are invite-only (SPEC §13.2 stays intact).
	AllowSignup bool `yaml:"allowSignup"`

	// DisableAssistant (env NORTHPLANE_DISABLE_ASSISTANT=true /
	// `disableAssistant: true`) switches the embedded Stept assistant
	// (chat widget + product tours) off at runtime: server-rendered pages
	// omit the snippet and the SPA skips injecting the loader. Default on.
	DisableAssistant bool `yaml:"disableAssistant"`
}

// TTSConfig holds server-wide text-to-speech settings; the per-tenant
// voice/engine choices live in tts-profile resources.
type TTSConfig struct {
	// Commands is the allowlist for the "command" engine: bare executable
	// names (resolved via PATH) or exact absolute paths a tts-profile may
	// run (profiles only need config:write, so arbitrary commands are not
	// permitted by default). Empty = built-in list of known TTS binaries
	// (piper, espeak-ng, flite, say, mimic3, …); ["*"] = any.
	Commands []string `yaml:"commands"`
	// CacheDir stores synthesized audio (default <dataDir>/tts-cache).
	CacheDir string `yaml:"cacheDir"`
	// CacheMaxMB bounds the cache (default 256 MB); least recently used
	// clips are evicted first.
	CacheMaxMB int `yaml:"cacheMaxMb"`
	// CacheTTL drops clips not used for this long (default 168h).
	CacheTTL time.Duration `yaml:"cacheTtl"`
}

// TTSCacheDir returns the synthesized-audio cache directory.
func (c Config) TTSCacheDir() string {
	if c.TTS.CacheDir != "" {
		return c.TTS.CacheDir
	}
	return filepath.Join(c.DataDir, "tts-cache")
}

// StorageConfig selects the relational backend (SPEC §7.3): empty DSN ⇒
// embedded SQLite under DataDir; "postgres://…" ⇒ PostgreSQL.
type StorageConfig struct {
	DSN string `yaml:"dsn"`
	// EventRetention: months of event segments/partitions to keep.
	EventRetentionMonths int `yaml:"eventRetentionMonths"`
}

// TLSConfig: certificate pair or autocert; plain HTTP only for
// localhost/dev (A-15.10: no plaintext fallback in production).
type TLSConfig struct {
	CertFile string `yaml:"certFile"`
	KeyFile  string `yaml:"keyFile"`
	// Insecure allows ListenAndServe without TLS — refused unless the
	// listener is loopback or explicitly forced (dev mode).
	Insecure bool `yaml:"insecure"`
}

// OIDCConfig for human SSO (SPEC §11.2).
type OIDCConfig struct {
	Issuer       string   `yaml:"issuer"`
	ClientID     string   `yaml:"clientId"`
	ClientSecret string   `yaml:"clientSecret"`
	Scopes       []string `yaml:"scopes"`      // default: openid profile email groups
	GroupsClaim  string   `yaml:"groupsClaim"` // default "groups"
	AdminGroup   string   `yaml:"adminGroup"`  // bootstrap mapping
}

// LDAPConfig drives directory user synchronisation and directory login
// (SPEC §11.2): users are periodically mirrored into the local user
// table (subject "ldap|…"), groups map onto roles via Role.IdPGroups,
// and the login form verifies directory users with a search-then-bind.
// Linux servers are the supported deployment target for directory sync.
type LDAPConfig struct {
	URL                string `yaml:"url"`      // ldap://host:389 or ldaps://host:636
	StartTLS           bool   `yaml:"startTls"` // upgrade ldap:// with StartTLS
	InsecureSkipVerify bool   `yaml:"insecureSkipVerify"`

	BindDN       string `yaml:"bindDn"`       // service account for sync/search
	BindPassword string `yaml:"bindPassword"` // env: NORTHPLANE_LDAP_BIND_PASSWORD

	BaseDN     string `yaml:"baseDn"`
	UserFilter string `yaml:"userFilter"` // default (&(objectClass=person)(mail=*))
	UserAttr   string `yaml:"userAttr"`   // login/e-mail attribute, default mail
	NameAttr   string `yaml:"nameAttr"`   // display name, default cn
	IDAttr     string `yaml:"idAttr"`     // stable id (entryUUID/objectGUID); empty = DN

	GroupAttr   string `yaml:"groupAttr"`   // membership attribute, default memberOf
	GroupFilter string `yaml:"groupFilter"` // optional member search, {dn}/{user} placeholders
	GroupBaseDN string `yaml:"groupBaseDn"` // default baseDn

	SyncInterval   time.Duration `yaml:"syncInterval"`   // default 15m
	DefaultRoles   []string      `yaml:"defaultRoles"`   // when no group maps, default [viewer]
	AdminGroup     string        `yaml:"adminGroup"`     // group DN/CN bootstrap-mapped to admin
	DisableMissing bool          `yaml:"disableMissing"` // disable users gone from the directory
}

// Enabled reports whether directory sync is configured.
func (l LDAPConfig) Enabled() bool { return l.URL != "" }

// FederationConfig connects this instance to a main instance (SPEC §7.7
// variant B): the edge instance dials out, reports status and pulls its
// config bundle — no inbound connectivity to the customer site needed.
type FederationConfig struct {
	Mode               string        `yaml:"mode"`    // "" = standalone, "edge"
	MainURL            string        `yaml:"mainUrl"` // https://main.example.net
	Token              string        `yaml:"token"`   // np_… minted on main (scope sites:connect)
	Site               string        `yaml:"site"`    // site name registered on main
	Interval           time.Duration `yaml:"interval"`
	InsecureSkipVerify bool          `yaml:"insecureSkipVerify"`
	// ApplyConfig: pull the site bundle from main and apply it locally
	// (true = the edge is configured from the main instance).
	ApplyConfig *bool `yaml:"applyConfig"` // default true
}

// EdgeEnabled reports whether this instance runs as a connected edge.
func (f FederationConfig) EdgeEnabled() bool { return f.Mode == "edge" }

// ApplyConfigEnabled defaults to true when unset.
func (f FederationConfig) ApplyConfigEnabled() bool {
	return f.ApplyConfig == nil || *f.ApplyConfig
}

// AIConfig per SPEC §10.2.
type AIConfig struct {
	Provider         string          `yaml:"provider"` // anthropic | azure-openai | openai-compat | none
	Endpoint         string          `yaml:"endpoint"`
	APIKeyEnv        string          `yaml:"apiKeyEnv"` // env var holding the key (never the key itself)
	APIKey           string          `yaml:"apiKey"`    // discouraged; for gateways with static keys
	Model            string          `yaml:"model"`
	ModelDeep        string          `yaml:"modelDeep"`
	MaxMonthlyTokens int64           `yaml:"maxMonthlyTokens"`
	Redaction        RedactionConfig `yaml:"redaction"`
}

// RedactionConfig drives the PII pipeline before any LLM call (§10.1/§13.6).
type RedactionConfig struct {
	Hostnames      string   `yaml:"hostnames"` // "" | "pseudonymize"
	CustomPatterns []string `yaml:"customPatterns"`
}

// BackupConfig for continuous backup (SPEC §14.2).
type BackupConfig struct {
	Target   string        `yaml:"target"` // directory or s3://… (dir in v1)
	Interval time.Duration `yaml:"interval"`
}

// DefaultDataDir returns the platform default data directory:
// /var/lib/northplane when running as root (the systemd/production
// case), otherwise a per-user directory so `northplaned` runs without
// privileges (macOS: ~/Library/Application Support/northplane, Linux:
// $XDG_DATA_HOME/northplane or ~/.local/share/northplane).
func DefaultDataDir() string {
	if os.Geteuid() == 0 {
		return "/var/lib/northplane"
	}
	if runtime.GOOS != "darwin" {
		if xdg := os.Getenv("XDG_DATA_HOME"); xdg != "" {
			return filepath.Join(xdg, "northplane")
		}
		if home, err := os.UserHomeDir(); err == nil {
			return filepath.Join(home, ".local", "share", "northplane")
		}
	}
	if dir, err := os.UserConfigDir(); err == nil {
		return filepath.Join(dir, "northplane")
	}
	return "/var/lib/northplane"
}

// DefaultConfigDir is where `northplaned init` writes config.yaml and
// secret.key: /etc/northplane as root, the per-user config directory
// otherwise (macOS: ~/Library/Application Support/northplane, Linux:
// ~/.config/northplane).
func DefaultConfigDir() string {
	if os.Geteuid() == 0 {
		return "/etc/northplane"
	}
	if dir, err := os.UserConfigDir(); err == nil {
		return filepath.Join(dir, "northplane")
	}
	return "/etc/northplane"
}

// DefaultConfigPath resolves the bootstrap config file: the system path
// when running as root or when it exists, the per-user path otherwise.
func DefaultConfigPath() string { return defaultPath("config.yaml") }

// DefaultAgentConfigPath is the np-agent equivalent of DefaultConfigPath.
func DefaultAgentConfigPath() string { return defaultPath("agent.yaml") }

func defaultPath(file string) string {
	system := filepath.Join("/etc/northplane", file)
	if os.Geteuid() == 0 {
		return system
	}
	if _, err := os.Stat(system); err == nil {
		return system
	}
	return filepath.Join(DefaultConfigDir(), file)
}

// Defaults returns the development-friendly default configuration.
// Listen binds loopback only: plaintext HTTP is acceptable there, and
// exposing the server requires an explicit listen + TLS decision
// (A-15.10: no accidental plaintext in production).
func Defaults() Config {
	return Config{
		Listen:          "127.0.0.1:8443",
		DataDir:         DefaultDataDir(),
		LogLevel:        "info",
		LogFormat:       "json",
		DeadManInterval: time.Minute,
		Storage:         StorageConfig{EventRetentionMonths: 12},
		OIDC:            OIDCConfig{Scopes: []string{"openid", "profile", "email", "groups"}, GroupsClaim: "groups"},
		LDAP: LDAPConfig{
			UserFilter: "(&(objectClass=person)(mail=*))",
			UserAttr:   "mail", NameAttr: "cn", GroupAttr: "memberOf",
			SyncInterval: 15 * time.Minute, DefaultRoles: []string{"viewer"},
			DisableMissing: true,
		},
		AI:         AIConfig{Provider: "none", Model: "claude-sonnet-4-6"},
		Backup:     BackupConfig{Interval: 5 * time.Minute},
		Federation: FederationConfig{Interval: time.Minute},
		TTS:        TTSConfig{CacheMaxMB: 256, CacheTTL: 7 * 24 * time.Hour},
	}
}

// Load reads path (if it exists), then applies NORTHPLANE_* overrides.
func Load(path string) (Config, error) {
	cfg := Defaults()
	if path != "" {
		b, err := os.ReadFile(path)
		switch {
		case err == nil:
			dec := yaml.NewDecoder(strings.NewReader(string(b)))
			dec.KnownFields(true)
			if err := dec.Decode(&cfg); err != nil && !errors.Is(err, io.EOF) {
				// io.EOF = empty/comment-only file: keep defaults rather
				// than refusing to start.
				return cfg, fmt.Errorf("config %s: %w", path, err)
			}
		case os.IsNotExist(err):
			// fine: env/defaults only
		default:
			return cfg, err
		}
	}
	applyEnv(&cfg)
	if cfg.PluginsDir == "" {
		cfg.PluginsDir = firstExisting(
			"/usr/lib/nagios/plugins", "/usr/lib64/nagios/plugins",
			"/usr/local/libexec/nagios", "/opt/homebrew/libexec",
			filepath.Join(cfg.DataDir, "plugins"),
		)
	}
	if err := cfg.Validate(); err != nil {
		return cfg, fmt.Errorf("config invalid: %w", err)
	}
	return cfg, nil
}

// Validate rejects configurations that cannot start a coherent server. It is
// deliberately conservative: it only flags combinations that are genuinely
// broken (an unparseable listen address, a TLS key without its cert, an
// incomplete OIDC block), never valid dev/demo defaults. Run by Load after
// env overrides are applied.
func (c Config) Validate() error {
	// Listen must be a parseable host:port. An empty host (":8443") and a
	// "0" port (kernel-assigned, used in tests) are both valid.
	if c.Listen == "" {
		return errors.New("listen: must be set (host:port, e.g. \"127.0.0.1:8443\")")
	}
	host, port, err := net.SplitHostPort(c.Listen)
	if err != nil {
		return fmt.Errorf("listen %q: not a valid host:port: %w", c.Listen, err)
	}
	if port == "" {
		return fmt.Errorf("listen %q: missing port", c.Listen)
	}
	if port != "0" {
		if _, err := net.LookupPort("tcp", port); err != nil {
			return fmt.Errorf("listen %q: invalid port: %w", c.Listen, err)
		}
	}
	_ = host // host is already validated by SplitHostPort; "" (all interfaces) is allowed

	// TLS coherence: cert and key are a pair — one without the other is a
	// misconfiguration that would silently fall back to plaintext.
	switch {
	case c.TLS.CertFile != "" && c.TLS.KeyFile == "":
		return errors.New("tls.certFile set without tls.keyFile")
	case c.TLS.KeyFile != "" && c.TLS.CertFile == "":
		return errors.New("tls.keyFile set without tls.certFile")
	}

	// OIDC completeness: if the block is touched at all (any field set),
	// require the two fields the flow cannot work without. The Scopes/
	// GroupsClaim defaults are always present, so they don't count as "set".
	oidcTouched := c.OIDC.Issuer != "" || c.OIDC.ClientID != "" ||
		c.OIDC.ClientSecret != "" || c.OIDC.AdminGroup != ""
	if oidcTouched {
		if c.OIDC.Issuer == "" {
			return errors.New("oidc configured but oidc.issuer is empty")
		}
		if c.OIDC.ClientID == "" {
			return errors.New("oidc configured but oidc.clientId is empty")
		}
	}

	// AI provider must be one of the known values; everything else (key,
	// endpoint) is the AI subsystem's concern and degrades gracefully.
	switch c.AI.Provider {
	case "", "none", "anthropic", "azure-openai", "openai-compat":
	default:
		return fmt.Errorf("ai.provider %q: must be one of none|anthropic|azure-openai|openai-compat", c.AI.Provider)
	}

	// LDAP coherence: a touched block needs url + baseDn; a bind DN
	// without its password silently degrades to anonymous bind — refuse.
	if c.LDAP.Enabled() || c.LDAP.BindDN != "" || c.LDAP.BaseDN != "" {
		if c.LDAP.URL == "" {
			return errors.New("ldap configured but ldap.url is empty")
		}
		if !strings.HasPrefix(c.LDAP.URL, "ldap://") && !strings.HasPrefix(c.LDAP.URL, "ldaps://") {
			return fmt.Errorf("ldap.url %q: must start with ldap:// or ldaps://", c.LDAP.URL)
		}
		if c.LDAP.BaseDN == "" {
			return errors.New("ldap configured but ldap.baseDn is empty")
		}
		if c.LDAP.BindDN != "" && c.LDAP.BindPassword == "" {
			return errors.New("ldap.bindDn set without ldap.bindPassword (set it or NORTHPLANE_LDAP_BIND_PASSWORD)")
		}
	}

	// Federation: edge mode needs the main URL, a token and a site name.
	switch c.Federation.Mode {
	case "", "edge":
	default:
		return fmt.Errorf("federation.mode %q: must be empty or \"edge\"", c.Federation.Mode)
	}
	if c.Federation.EdgeEnabled() {
		if !strings.HasPrefix(c.Federation.MainURL, "https://") &&
			!strings.HasPrefix(c.Federation.MainURL, "http://") {
			return fmt.Errorf("federation.mainUrl %q: must be an http(s) URL", c.Federation.MainURL)
		}
		if c.Federation.Token == "" {
			return errors.New("federation.mode edge requires federation.token (mint on the main instance, scope sites:connect)")
		}
		if c.Federation.Site == "" {
			return errors.New("federation.mode edge requires federation.site (the site name registered on the main instance)")
		}
	}

	return nil
}

func firstExisting(paths ...string) string {
	for _, p := range paths {
		if st, err := os.Stat(p); err == nil && st.IsDir() {
			return p
		}
	}
	return paths[len(paths)-1]
}

// applyEnv maps NORTHPLANE_SECTION_FIELD → fields (SPEC §15.2).
func applyEnv(c *Config) {
	str := func(key string, dst *string) {
		if v, ok := os.LookupEnv(key); ok {
			*dst = v
		}
	}
	str("NORTHPLANE_LISTEN", &c.Listen)
	str("NORTHPLANE_BASE_URL", &c.BaseURL)
	str("NORTHPLANE_DATA_DIR", &c.DataDir)
	str("NORTHPLANE_STORAGE_DSN", &c.Storage.DSN)
	str("NORTHPLANE_TLS_CERT_FILE", &c.TLS.CertFile)
	str("NORTHPLANE_TLS_KEY_FILE", &c.TLS.KeyFile)
	if v, ok := os.LookupEnv("NORTHPLANE_TLS_INSECURE"); ok {
		c.TLS.Insecure, _ = strconv.ParseBool(v)
	}
	if v, ok := os.LookupEnv("NORTHPLANE_TRUST_PROXY"); ok {
		c.TrustProxy, _ = strconv.ParseBool(v)
	}
	if v, ok := os.LookupEnv("NORTHPLANE_DEMO"); ok {
		c.Demo, _ = strconv.ParseBool(v)
	}
	if v, ok := os.LookupEnv("NORTHPLANE_ALLOW_SIGNUP"); ok {
		c.AllowSignup, _ = strconv.ParseBool(v)
	}
	if v, ok := os.LookupEnv("NORTHPLANE_DISABLE_ASSISTANT"); ok {
		c.DisableAssistant, _ = strconv.ParseBool(v)
	}
	str("NORTHPLANE_OIDC_ISSUER", &c.OIDC.Issuer)
	str("NORTHPLANE_OIDC_CLIENT_ID", &c.OIDC.ClientID)
	str("NORTHPLANE_OIDC_CLIENT_SECRET", &c.OIDC.ClientSecret)
	str("NORTHPLANE_LDAP_URL", &c.LDAP.URL)
	str("NORTHPLANE_LDAP_BIND_DN", &c.LDAP.BindDN)
	str("NORTHPLANE_LDAP_BIND_PASSWORD", &c.LDAP.BindPassword)
	str("NORTHPLANE_LDAP_BASE_DN", &c.LDAP.BaseDN)
	str("NORTHPLANE_FEDERATION_MODE", &c.Federation.Mode)
	str("NORTHPLANE_FEDERATION_MAIN_URL", &c.Federation.MainURL)
	str("NORTHPLANE_FEDERATION_TOKEN", &c.Federation.Token)
	str("NORTHPLANE_FEDERATION_SITE", &c.Federation.Site)
	str("NORTHPLANE_AI_PROVIDER", &c.AI.Provider)
	str("NORTHPLANE_AI_ENDPOINT", &c.AI.Endpoint)
	str("NORTHPLANE_AI_MODEL", &c.AI.Model)
	str("NORTHPLANE_AI_API_KEY_ENV", &c.AI.APIKeyEnv)
	str("NORTHPLANE_PLUGINS_DIR", &c.PluginsDir)
	str("NORTHPLANE_LOG_LEVEL", &c.LogLevel)
	str("NORTHPLANE_LOG_FORMAT", &c.LogFormat)
	str("NORTHPLANE_SECRET_KEY_FILE", &c.SecretKeyFile)
	str("NORTHPLANE_BACKUP_TARGET", &c.Backup.Target)
	str("NORTHPLANE_DEADMAN_URL", &c.DeadManURL)
	str("NORTHPLANE_TTS_CACHE_DIR", &c.TTS.CacheDir)
	if v, ok := os.LookupEnv("NORTHPLANE_TTS_COMMANDS"); ok {
		c.TTS.Commands = nil
		for _, p := range strings.Split(v, ",") {
			if p = strings.TrimSpace(p); p != "" {
				c.TTS.Commands = append(c.TTS.Commands, p)
			}
		}
	}
	if v, ok := os.LookupEnv("NORTHPLANE_EXEC_POOL_SIZE"); ok {
		if n, err := strconv.Atoi(v); err == nil {
			c.ExecPoolSize = n
		}
	}
}

// SQLitePath returns the core database path for embedded mode.
func (c Config) SQLitePath() string { return filepath.Join(c.DataDir, "core.db") }

// TSDBDir returns the metrics engine directory.
func (c Config) TSDBDir() string { return filepath.Join(c.DataDir, "tsdb") }

// ArtifactsDir stores E2E check artifacts (SPEC §8.6).
func (c Config) ArtifactsDir() string { return filepath.Join(c.DataDir, "artifacts") }

// UsePostgres reports whether the DSN selects the PostgreSQL backend.
func (c Config) UsePostgres() bool {
	return strings.HasPrefix(c.Storage.DSN, "postgres://") ||
		strings.HasPrefix(c.Storage.DSN, "postgresql://")
}

// Example renders the commented config file written by `northplaned
// init`. dataDir and secretKeyFile are interpolated directly (no
// post-hoc string replacement) so the generated file is always valid.
func Example(dataDir, secretKeyFile string) string {
	if dataDir == "" {
		dataDir = DefaultDataDir()
	}
	keyLine := ""
	if secretKeyFile != "" {
		keyLine = fmt.Sprintf("secretKeyFile: %q\n", secretKeyFile)
	}
	return `# Northplane bootstrap configuration (SPEC §15.2).
# Only pre-API settings live here — everything else is managed via API,
# UI or config bundles. Environment overrides: NORTHPLANE_*.

# Loopback default. To serve the network, set listen: ":8443" AND
# configure TLS below (plaintext on non-loopback refuses to start).
listen: "127.0.0.1:8443"
#baseUrl: "https://monitoring.example.net"
dataDir: ` + fmt.Sprintf("%q", dataDir) + `
` + keyLine + `
storage:
  # Empty dsn = embedded SQLite under dataDir (default).
  # PostgreSQL server mode: "postgres://np:secret@db:5432/northplane"
  dsn: ""
  eventRetentionMonths: 12

tls:
  certFile: ""
  keyFile: ""
  # insecure: true   # dev only; refused on non-loopback listeners

#oidc:
#  issuer: "https://login.microsoftonline.com/<tenant>/v2.0"
#  clientId: "…"
#  clientSecret: "…"
#  adminGroup: "<entra-group-object-id>"

# Directory user sync + login (LDAP / Active Directory).
#ldap:
#  url: "ldaps://dc1.example.net:636"
#  bindDn: "cn=svc-northplane,ou=service,dc=example,dc=net"
#  bindPassword: "…"        # or NORTHPLANE_LDAP_BIND_PASSWORD
#  baseDn: "dc=example,dc=net"
#  userFilter: "(&(objectClass=person)(mail=*))"
#  userAttr: mail            # AD: userPrincipalName
#  idAttr: ""                # AD: objectGUID, OpenLDAP: entryUUID (stable across DN moves)
#  groupAttr: memberOf
#  adminGroup: "cn=northplane-admins,ou=groups,dc=example,dc=net"
#  syncInterval: 15m
#  defaultRoles: [viewer]
#  disableMissing: true

# Connect this instance to a main instance (customer-site edge mode).
#federation:
#  mode: edge
#  mainUrl: "https://main.example.net"
#  token: "np_…"             # minted on main, scope sites:connect
#  site: "customer-a"
#  interval: 60s

ai:
  provider: none     # anthropic | azure-openai | openai-compat | none
  #endpoint: "https://api.anthropic.com"
  #apiKeyEnv: ANTHROPIC_API_KEY
  #model: claude-sonnet-4-6
  #modelDeep: claude-opus-4-8
  #maxMonthlyTokens: 50000000

backup:
  target: ""          # directory for continuous backup; empty = disabled
  interval: 5m

# Text-to-speech for voice alarms (engines/voices are tts-profile resources).
#tts:
#  commands: [piper, espeak-ng, flite, say]   # executables the "command" engine may run; ["*"] = any
#  cacheDir: ""        # synthesized audio cache, default <dataDir>/tts-cache
#  cacheMaxMb: 256
#  cacheTtl: 168h

#deadManUrl: "https://hc-ping.com/<uuid>"   # SPEC §14.2 dead-man switch
`
}
